{
  "hash": "19cbc8aa229f5f4a95638db98f4385d5",
  "result": {
    "markdown": "---\ntitle: \"Wine dataset exploratory data analysis\"\nauthor: \"Bhanu Varaprasad\"\ndate: \"2023-12-12\"\ncategories: [news, code, analysis,plotly,plot]\nimage: \"profile.jpg\"\n---\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required libraries\nlibrary(ggplot2)\n\n# Load the dataset\nwine_data <- read.csv(\"C:/Users/YOJANA/Downloads/AN/KN/WineQT.csv\")\n\n# Explore the structure of the dataset\nstr(wine_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t1143 obs. of  13 variables:\n $ fixed.acidity       : num  7.4 7.8 7.8 11.2 7.4 7.4 7.9 7.3 7.8 6.7 ...\n $ volatile.acidity    : num  0.7 0.88 0.76 0.28 0.7 0.66 0.6 0.65 0.58 0.58 ...\n $ citric.acid         : num  0 0 0.04 0.56 0 0 0.06 0 0.02 0.08 ...\n $ residual.sugar      : num  1.9 2.6 2.3 1.9 1.9 1.8 1.6 1.2 2 1.8 ...\n $ chlorides           : num  0.076 0.098 0.092 0.075 0.076 0.075 0.069 0.065 0.073 0.097 ...\n $ free.sulfur.dioxide : num  11 25 15 17 11 13 15 15 9 15 ...\n $ total.sulfur.dioxide: num  34 67 54 60 34 40 59 21 18 65 ...\n $ density             : num  0.998 0.997 0.997 0.998 0.998 ...\n $ pH                  : num  3.51 3.2 3.26 3.16 3.51 3.51 3.3 3.39 3.36 3.28 ...\n $ sulphates           : num  0.56 0.68 0.65 0.58 0.56 0.56 0.46 0.47 0.57 0.54 ...\n $ alcohol             : num  9.4 9.8 9.8 9.8 9.4 9.4 9.4 10 9.5 9.2 ...\n $ quality             : int  5 5 5 6 5 5 5 7 7 5 ...\n $ Id                  : int  0 1 2 3 4 5 6 7 8 10 ...\n```\n:::\n\n```{.r .cell-code}\n# Display summary statistics\nsummary(wine_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n fixed.acidity    volatile.acidity  citric.acid     residual.sugar  \n Min.   : 4.600   Min.   :0.1200   Min.   :0.0000   Min.   : 0.900  \n 1st Qu.: 7.100   1st Qu.:0.3925   1st Qu.:0.0900   1st Qu.: 1.900  \n Median : 7.900   Median :0.5200   Median :0.2500   Median : 2.200  \n Mean   : 8.311   Mean   :0.5313   Mean   :0.2684   Mean   : 2.532  \n 3rd Qu.: 9.100   3rd Qu.:0.6400   3rd Qu.:0.4200   3rd Qu.: 2.600  \n Max.   :15.900   Max.   :1.5800   Max.   :1.0000   Max.   :15.500  \n   chlorides       free.sulfur.dioxide total.sulfur.dioxide    density      \n Min.   :0.01200   Min.   : 1.00       Min.   :  6.00       Min.   :0.9901  \n 1st Qu.:0.07000   1st Qu.: 7.00       1st Qu.: 21.00       1st Qu.:0.9956  \n Median :0.07900   Median :13.00       Median : 37.00       Median :0.9967  \n Mean   :0.08693   Mean   :15.62       Mean   : 45.91       Mean   :0.9967  \n 3rd Qu.:0.09000   3rd Qu.:21.00       3rd Qu.: 61.00       3rd Qu.:0.9978  \n Max.   :0.61100   Max.   :68.00       Max.   :289.00       Max.   :1.0037  \n       pH          sulphates         alcohol         quality     \n Min.   :2.740   Min.   :0.3300   Min.   : 8.40   Min.   :3.000  \n 1st Qu.:3.205   1st Qu.:0.5500   1st Qu.: 9.50   1st Qu.:5.000  \n Median :3.310   Median :0.6200   Median :10.20   Median :6.000  \n Mean   :3.311   Mean   :0.6577   Mean   :10.44   Mean   :5.657  \n 3rd Qu.:3.400   3rd Qu.:0.7300   3rd Qu.:11.10   3rd Qu.:6.000  \n Max.   :4.010   Max.   :2.0000   Max.   :14.90   Max.   :8.000  \n       Id      \n Min.   :   0  \n 1st Qu.: 411  \n Median : 794  \n Mean   : 805  \n 3rd Qu.:1210  \n Max.   :1597  \n```\n:::\n\n```{.r .cell-code}\n# Check for missing values\nsum(is.na(wine_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\n# Data visualization for each feature\n# You can customize the plots based on your preferences and requirements\n\n# Box plots for each input variable\nfor (col in 1:11) {\n  ggplot(wine_data, aes(x = quality, y = wine_data[, col])) +\n    geom_boxplot(fill = \"skyblue\", color = \"steelblue\") +\n    labs(title = paste(\"Box plot of\", names(wine_data)[col]))\n}\n\n# Correlation matrix\ncor_matrix <- cor(wine_data[, 1:11])\nggplot(data = as.data.frame(as.table(cor_matrix)), aes(x = Var1, y = Var2, fill = Freq)) +\n  geom_tile(color = \"white\") +\n  scale_fill_gradient2(low = \"blue\", high = \"red\", mid = \"white\", midpoint = 0, limit = c(-1, 1), space = \"Lab\",\n                       name = \"Correlation\") +\n  theme_minimal() +\n  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 10, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Histogram of the target variable (quality)\nggplot(wine_data, aes(x = quality)) +\n  geom_histogram(binwidth = 1, fill = \"skyblue\", color = \"steelblue\") +\n  labs(title = \"Histogram of Wine Quality\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Class distribution bar plot\nggplot(wine_data, aes(x = as.factor(quality), fill = as.factor(quality))) +\n  geom_bar() +\n  labs(title = \"Class Distribution of Wine Quality\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# Pair plots for a subset of variables\n# You can customize the subset based on your preferences\nsubset_vars <- c(\"fixed acidity\", \"volatile acidity\", \"citric acid\", \"residual sugar\", \"quality\")\n\n# Replace spaces in column names with dots and use backticks\ncolnames(wine_data) <- gsub(\" \", \".\", colnames(wine_data))\n\n# Check the column names to ensure they match with the actual names in your dataset\ncolnames(wine_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"fixed.acidity\"        \"volatile.acidity\"     \"citric.acid\"         \n [4] \"residual.sugar\"       \"chlorides\"            \"free.sulfur.dioxide\" \n [7] \"total.sulfur.dioxide\" \"density\"              \"pH\"                  \n[10] \"sulphates\"            \"alcohol\"              \"quality\"             \n[13] \"Id\"                  \n```\n:::\n\n```{.r .cell-code}\n# Subset of variables for pair plots\nsubset_vars <- c(\"fixed.acidity\", \"volatile.acidity\", \"citric.acid\", \"residual.sugar\", \"quality\")\n\n# Scatter plot matrix for a subset of variables\npairs(wine_data[, subset_vars], pch = 16, col = as.factor(wine_data$quality))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# Correlation heatmap\nlibrary(corrplot)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'corrplot' was built under R version 4.3.2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\ncorrplot 0.92 loaded\n```\n:::\n\n```{.r .cell-code}\ncorrplot(cor(wine_data[, 1:11]), method = \"color\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-5.png){width=672}\n:::\n:::\n\n\n***The summary statistics provide insights into the key characteristics of the dataset related to red variants of Portuguese \"Vinho Verde\" wine. The physicochemical properties of the wines vary across the sampled instances. The mean fixed acidity is 8.311, with a range from 4.6 to 15.9. Volatile acidity ranges from 0.12 to 1.58, with a mean of 0.5313. Citric acid content ranges from 0 to 1, with a mean of 0.2684. Residual sugar has a mean of 2.532 and ranges from 0.9 to 15.5. Chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, and alcohol also exhibit varying ranges and means. The quality scores, ranging from 3 to 8, have a mean of 5.657. The dataset comprises 1598 instances, with an 'Id' column ranging from 0 to 1597. The summary provides a concise overview of the dataset's central tendencies and variability, laying the foundation for further exploration and modeling.***\n\n------------------------------------------------------------------------\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}